[package]
name = "affix-grammar-js"
version = "0.1.3"
authors = ["eignnx <eignnx@gmail.com>"]
edition = "2018"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.59"
libaffix = { path = "../libaffix" }
